# config/pipelines.yml
- pipeline.id: pipeline_sample_randomuserapi
  path.config: "/usr/share/logstash/pipeline/pipeline_sample_randomuserapi.conf"

# - pipeline.id: pipeline_jira
#   path.config: "/usr/share/logstash/pipeline/pipeline_jira.conf"
